groups:
    - common
recipes:
    global:
    mac_os_x:
        - sudoalt::default
        - osxdefaults::set_computer_name
attributes:
    git:
        name: Ramzi Akremi
        email: ramzi.akremi@gmail.com
    osxdefaults:
        computername: Linus
    authorization:
        sudo:
            users:
                - rakr
            passwordless: true
            include_sudoers_d: true

