recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
        - applications::sublime_text_3

attributes:
    homebrewalt:
        cask_apps:
            - dropbox
            - alfred
            - vagrant
            - hazel
            - flash-player
            - iterm2
            - vlc
            - mavensmate
            - omnigraffle
